#!/usr/bin/env bash

source ./scripts/_need-user

docker run \
  -it \
  --rm \
  -v $1:$1:ro \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  $need_user \
  -e HOME="$(pwd)" \
  waterlink/gapps \
  gapps auth $1 --no-launch-browser
